//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangThanhTu_2122110051.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
    }
}
