//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangThanhTu_2122110051.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long Id { get; set; }
        public Nullable<long> User_id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public Nullable<long> ReplayId { get; set; }
        public byte Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
