//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangThanhTu_2122110051.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public long Id { get; set; }
        public long Order_id { get; set; }
        public long Product_id { get; set; }
        public double Price { get; set; }
        public int Qty { get; set; }
        public double Discount { get; set; }
        public double Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
