//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangThanhTu_2122110051.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public long Id { get; set; }
        public long User_id { get; set; }
        public string Delivery_name { get; set; }
        public string Delivery_gender { get; set; }
        public string Delivery_email { get; set; }
        public string Delivery_phone { get; set; }
        public string Delivery_address { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
        public byte Status { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
